/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.randomplaydanceplaylistgenerator2;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.*;
import javax.swing.UIManager;
import java.io.*;
import java.nio.file.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author benny
 */
public class MainFrameFlatLaf extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrameFlatLaf.class.getName());
    private static final File COUNTDOWN_FOLDER = new File("./res/countdown-audios");
    private static final String FFMPEG_FILEPATH = "./res/ffmpeg/ffmpeg.exe";
    private JFileChooser fc, fcFolder;
    private DefaultTableModel dtmCountdown, dtmPlaylist;
    private String countdownCanonicalPath;

    /**
     * Creates new form MainFrameFlatLaf
     */
    public MainFrameFlatLaf() {
        try { // set look of GUI
            UIManager.setLookAndFeel( new FlatDarkLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        initComponents();
        getContentPane().setBackground(new java.awt.Color(60, 63, 65));
        
        // initialise countdown table and set canon path
        tblCountdown.setDefaultEditor(Object.class, null);
        
        updateCountdowns();
        try {
            countdownCanonicalPath = COUNTDOWN_FOLDER.getCanonicalPath();
        } catch (IOException ex) {
            System.getLogger(MainFrameFlatLaf.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        // initialise playlist table
        tblPlaylist.setDefaultEditor(Object.class, null);
        
        // initialise file/folder choosers
        fc = new JFileChooser();
        fc.setMultiSelectionEnabled(true);
        fcFolder = new JFileChooser();
        fcFolder.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddFile = new javax.swing.JButton();
        btnAddFolder = new javax.swing.JButton();
        lbCountdown = new javax.swing.JLabel();
        btnDeleteSong = new javax.swing.JButton();
        lbPlaylist = new javax.swing.JLabel();
        btnPlaylistUp = new javax.swing.JButton();
        btnPlaylistDown = new javax.swing.JButton();
        spCountdown = new javax.swing.JScrollPane();
        tblCountdown = new javax.swing.JTable();
        spAudio = new javax.swing.JScrollPane();
        tblPlaylist = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnExport = new javax.swing.JButton();
        btnCountdownDelete = new javax.swing.JButton();
        cbFileFormat = new javax.swing.JComboBox<>();
        lbLocation = new javax.swing.JLabel();
        btnLocation = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        tfFileName = new javax.swing.JTextField();
        btnCountdownAdd = new javax.swing.JButton();
        tfLocation = new javax.swing.JTextField();
        lbFileName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RPD Playlist Generator");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon.png")).getImage());
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(700, 420));

        btnAddFile.setText("Add File");
        btnAddFile.addActionListener(this::btnAddFileActionPerformed);

        btnAddFolder.setText("Add Folder");
        btnAddFolder.setToolTipText("");
        btnAddFolder.addActionListener(this::btnAddFolderActionPerformed);

        lbCountdown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCountdown.setText("Countdown Audio");

        btnDeleteSong.setText("Delete Song");
        btnDeleteSong.addActionListener(this::btnDeleteSongActionPerformed);

        lbPlaylist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlaylist.setText("Playlist Songs");

        btnPlaylistUp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPlaylistUp.setText("↑");
        btnPlaylistUp.setFocusable(false);
        btnPlaylistUp.addActionListener(this::btnPlaylistUpActionPerformed);

        btnPlaylistDown.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPlaylistDown.setText("↓");
        btnPlaylistDown.setFocusable(false);
        btnPlaylistDown.addActionListener(this::btnPlaylistDownActionPerformed);

        spCountdown.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblCountdown.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCountdown.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblCountdown.setFillsViewportHeight(true);
        spCountdown.setViewportView(tblCountdown);

        tblPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "FilePath"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPlaylist.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblPlaylist.setFillsViewportHeight(true);
        tblPlaylist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblPlaylistKeyPressed(evt);
            }
        });
        spAudio.setViewportView(tblPlaylist);

        btnExport.setForeground(new java.awt.Color(0, 255, 0));
        btnExport.setText("Export");
        btnExport.addActionListener(this::btnExportActionPerformed);

        btnCountdownDelete.setText("Delete Countdown Audio");
        btnCountdownDelete.addActionListener(this::btnCountdownDeleteActionPerformed);

        cbFileFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "File Format", ".mp3", ".wav", ".m4a", ".ogg", ".flac" }));

        lbLocation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbLocation.setText("Export Location");
        lbLocation.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lbLocation.setVerifyInputWhenFocusTarget(false);

        btnLocation.setText("Select Location");
        btnLocation.addActionListener(this::btnLocationActionPerformed);

        btnClear.setForeground(new java.awt.Color(255, 0, 0));
        btnClear.setText("Clear Songs");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnCountdownAdd.setText("Add Countdown Audio");
        btnCountdownAdd.addActionListener(this::btnCountdownAddActionPerformed);

        lbFileName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbFileName.setText("Output File Name");
        lbFileName.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCountdownDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCountdownAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbFileName)
                        .addGap(382, 382, 382))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbFileFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfLocation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLocation)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCountdownAdd)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLocation))
                            .addComponent(lbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbFileFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnClear)
                                .addComponent(btnExport))
                            .addComponent(tfFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCountdownDelete)
                            .addComponent(lbFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        cbFileFormat.getAccessibleContext().setAccessibleName("File Format");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbCountdown, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(spCountdown, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddFile, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteSong))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spAudio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPlaylistUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlaylistDown))))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCountdown, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPlaylist)
                    .addComponent(btnAddFile)
                    .addComponent(btnAddFolder)
                    .addComponent(btnDeleteSong))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnPlaylistUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlaylistDown)
                        .addGap(0, 168, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spAudio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(spCountdown, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnPlaylistUp.getAccessibleContext().setAccessibleName("Move Song Up");
        btnPlaylistDown.getAccessibleContext().setAccessibleName("Move Song Down");

        setSize(new java.awt.Dimension(712, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // common functions
    private void showErrorDialog(String message) {
        JOptionPane.showMessageDialog(this,
                message,
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    
    private int getSelectedCountdownIndex() {
        int selectedRow = tblCountdown.getSelectedRow();
        if (selectedRow == -1) {
            showErrorDialog("No countdown selected");
        } return selectedRow;
    }
    
    private boolean checkIfAudioFile(File file) {
        try {
            String mimeType = Files.probeContentType(file.toPath());
            if (mimeType.startsWith("audio/")) {
                return true;
            }
        } catch (Exception e) {
            showErrorDialog(e.getLocalizedMessage());
        }
        return false;
    }
    
    // playlist functions
    private void btnAddFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFolderActionPerformed
        int returnVal = fcFolder.showOpenDialog(MainFrameFlatLaf.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File folder = fcFolder.getSelectedFile();
            File[] files = folder.listFiles();
            addSongsToPlaylist(files);
        }
    }//GEN-LAST:event_btnAddFolderActionPerformed

    private void btnAddFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFileActionPerformed
        int returnVal = fc.showOpenDialog(MainFrameFlatLaf.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File[] files = fc.getSelectedFiles();
            addSongsToPlaylist(files);
        }
    }//GEN-LAST:event_btnAddFileActionPerformed
    
    private void addSongsToPlaylist(File[] files) {
        if (files != null) {
            List<String> nonAudioFiles = new ArrayList<String>();
            for (File file : files) {
                if (file.isFile() && checkIfAudioFile(file)) {
                    addSongToPlaylist(file);
                } else if (file.isFile()) {
                    nonAudioFiles.add(file.getName());
                }
            }
            if (!nonAudioFiles.isEmpty()) {
                showErrorDialog("Selected files aren't audio files:\n" + String.join("\n", nonAudioFiles));
            }
        } else {
            showErrorDialog("Selected folder is empty");
        }
    }
    
    private void addSongToPlaylist(File file) {
        // add attributes to array - name and path
        Object[] fileAttributes = new Object[2];
        fileAttributes[0] = file.getName();
        fileAttributes[1] = file.getPath();
        
        // add array to table
        dtmPlaylist = (DefaultTableModel) tblPlaylist.getModel();
        dtmPlaylist.addRow(fileAttributes);
    }

    private void btnDeleteSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSongActionPerformed
        int playlistIndex = getSelectedPlaylistIndex();
        if (playlistIndex == -1) return;
        dtmPlaylist = (DefaultTableModel) tblPlaylist.getModel();
        dtmPlaylist.removeRow(playlistIndex);
    }//GEN-LAST:event_btnDeleteSongActionPerformed

    private void btnPlaylistUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaylistUpActionPerformed
        movePlaylistSong(false);
    }//GEN-LAST:event_btnPlaylistUpActionPerformed

    private void btnPlaylistDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaylistDownActionPerformed
        movePlaylistSong(true);
    }//GEN-LAST:event_btnPlaylistDownActionPerformed
    
    private void movePlaylistSong(boolean isDown) {
        int playlistIndex = getSelectedPlaylistIndex();
        // return if index not found or already at top of playlist
        int playlistEndIndex = 0;
        if (isDown) {
            playlistEndIndex = tblPlaylist.getRowCount() - 1;
        }
        if (playlistIndex == -1 || playlistIndex == playlistEndIndex) return;
        dtmPlaylist = (DefaultTableModel) tblPlaylist.getModel();
        Object[] rowToSwap = new Object[dtmPlaylist.getColumnCount()];
        for (int i = 0; i < dtmPlaylist.getColumnCount(); i++) {
            rowToSwap[i] = dtmPlaylist.getValueAt(playlistIndex, i);
        }
        dtmPlaylist.removeRow(playlistIndex);
        if (isDown) {
            playlistIndex++;
        } else {
            playlistIndex--;
        }
        dtmPlaylist.insertRow(playlistIndex, rowToSwap);
        tblPlaylist.setRowSelectionInterval(playlistIndex, playlistIndex);
    }
    
    private int getSelectedPlaylistIndex() {
        int selectedRow = tblPlaylist.getSelectedRow();

        if (selectedRow == -1) {
            showErrorDialog("No song selected");
        }
        return selectedRow;
    }

    // countdown functions
    private void btnCountdownAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountdownAddActionPerformed
        int returnVal = fc.showOpenDialog(MainFrameFlatLaf.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File countdownFile = fc.getSelectedFile();
            if (checkIfAudioFile(countdownFile)) {
                String countdownFileName = countdownFile.getName();
                try {
                    Files.copy(countdownFile.toPath(), Paths.get(countdownCanonicalPath + "/" + countdownFileName));
                    updateCountdowns();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                showErrorDialog("Selected file isn't an audio file:\n" + countdownFile.getName());
            }
        }
    }//GEN-LAST:event_btnCountdownAddActionPerformed
   
    private void btnCountdownDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountdownDeleteActionPerformed
        int countdownIndex = getSelectedCountdownIndex();
        if (countdownIndex == -1) return;
        
        // get selected countdown
        dtmCountdown = (DefaultTableModel) tblCountdown.getModel();
        String selectedCountdown = dtmCountdown.getValueAt(countdownIndex, 0).toString();
        File countdownFile = new File(countdownCanonicalPath + "/" + selectedCountdown);
        
        if (countdownFile.delete()) {
            updateCountdowns();
        } else {
            showErrorDialog("Countdown couldn't be deleted");
        }
    }//GEN-LAST:event_btnCountdownDeleteActionPerformed

    private void updateCountdowns() {
        File[] listOfFiles = COUNTDOWN_FOLDER.listFiles();
        if (listOfFiles != null) {
            List<Object[]> fileList = new ArrayList<>();
            for (File file : listOfFiles) {
                if (file.isFile()) { // add each countdown to list
                    Object[] fileAttributes = {file.getName()};
                    fileList.add(fileAttributes);
                }
            }
            dtmCountdown = (DefaultTableModel) tblCountdown.getModel();
            dtmCountdown.setRowCount(0);
            for (Object[] row : fileList) {
                dtmCountdown.addRow(row);
            }
        }
    }

    // location functions
    private void btnLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationActionPerformed
        int returnVal = fcFolder.showOpenDialog(MainFrameFlatLaf.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File folder = fcFolder.getSelectedFile();
            tfLocation.setText(folder.getPath());
        }
    }//GEN-LAST:event_btnLocationActionPerformed

    // clear and export functions
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        dtmPlaylist = (DefaultTableModel) tblPlaylist.getModel();
        dtmPlaylist.setRowCount(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // data validation
        int countdownIndex = getSelectedCountdownIndex();
        if (countdownIndex == -1) return;
        if (isPlaylistEmpty()) return;
        if (!isPathValid()) return;
        if (!doesOutputFileNameExist()) return;
        
        // get selected countdown
        dtmCountdown = (DefaultTableModel) tblCountdown.getModel();
        String selectedCountdown = dtmCountdown.getValueAt(countdownIndex, 0).toString();
        
        try { // create ffmpeg command
            
            List<String> ffmpegCommand = new ArrayList<>();
            // ffmpegCommand.add("ffmpeg");
            ffmpegCommand.add(new File(FFMPEG_FILEPATH).getAbsolutePath());
            ffmpegCommand.add("-y");  // overwrite existing file if it exists
            
            // add each song in playlist with countdown before
            for (int i = 0; i < dtmPlaylist.getRowCount(); i++) {
                ffmpegCommand.add("-i"); // countdown
                ffmpegCommand.add(countdownCanonicalPath + "/" + selectedCountdown);
                ffmpegCommand.add("-i"); // song
                ffmpegCommand.add(dtmPlaylist.getValueAt(i, 1).toString());
            }
            
            // concat filter to combine multiple audio files
            StringBuilder concatFilter = new StringBuilder();
            
            // [0:a][1:a][2:a][3:a]... for each audio file
            int totalInputs = dtmPlaylist.getRowCount() * 2;
            for (int i = 0; i < totalInputs; i++) {
                concatFilter.append("[").append(i).append(":a]");
            }
            
            concatFilter.append("concat=n=")      // concatenate all files
                .append(totalInputs)        // n = number of files
                .append(":v=0:a=1[out]");   // v=0 = no video; a=1 = 1 audio output 
            
            ffmpegCommand.add("-filter_complex");
            ffmpegCommand.add(concatFilter.toString());
            
            // use the output from the filter
            ffmpegCommand.add("-map");
            ffmpegCommand.add("[out]");
            
            // set output format
            ffmpegCommand.add("-ac"); // number of audio channels
            ffmpegCommand.add("2");   // 2 - stereo
            ffmpegCommand.add("-ar"); // sample rate
            ffmpegCommand.add("44100");
            
            // set encoder for each file format
            ffmpegCommand.add("-c:a");
            ffmpegCommand.add(getEncoder());
            
            // set output location
            ffmpegCommand.add(tfLocation.getText() + File.separator + getFileName() + getFileFormat());
            
            // run and show ffmpeg output
            ProcessBuilder pbExport = new ProcessBuilder(ffmpegCommand);
            pbExport.inheritIO();
            Process process = pbExport.start();
            process.waitFor();
            
            JOptionPane.showMessageDialog(this,
                "Export Complete!",
                "Success",
                JOptionPane.PLAIN_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            showErrorDialog("Export failed: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnExportActionPerformed

    private void tblPlaylistKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPlaylistKeyPressed
        int keyCode = evt.getKeyCode();
        evt.consume();
        switch (keyCode) {
            case java.awt.event.KeyEvent.VK_UP:
                movePlaylistSong(false);
                break;
            case java.awt.event.KeyEvent.VK_DOWN:
                movePlaylistSong(true);
                break;
        }
    }//GEN-LAST:event_tblPlaylistKeyPressed
    
    private boolean isPlaylistEmpty() {
        if (tblPlaylist.getRowCount() == 0) {
            showErrorDialog("Playlist is empty");
            return true;
        } return false;
    }
    
    private boolean isPathValid() {
        String filepath = tfLocation.getText();
        if (!filepath.equals("")) {
            try {
                Paths.get(filepath);
                return true;
            } catch (InvalidPathException | NullPointerException ex) {} 
        } 
        showErrorDialog("Export path isn't valid");
        return false;
    }
    
    private boolean doesOutputFileNameExist() {
        if (tfFileName.getText().isEmpty()) {
            showErrorDialog("No output file name");
            return false;
        } return true;
    }
    
    private String getEncoder() {
        String encoder = switch (cbFileFormat.getSelectedItem().toString()) {
            case ".mp3" -> "libmp3lame";
            case ".wav" -> "pcm_s16le";
            case ".m4a" -> "aac";
            case ".ogg" -> "libvorbis";
            case ".flac" -> "flac";
            default -> "libmp3lame"; // not selecting should default to mp3
        };
        return encoder;
    }
    
    private String getFileName() {
        String fileName = tfFileName.getText();
        if (!fileName.equals("")) {
            return fileName;
        } return "output";
    }
    
    private String getFileFormat() {
        String fileFormat = cbFileFormat.getSelectedItem().toString();
        // not selecting should default to mp3
        if (fileFormat == "File Format") {
            fileFormat = ".mp3";
        }
        return fileFormat;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrameFlatLaf().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFile;
    private javax.swing.JButton btnAddFolder;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCountdownAdd;
    private javax.swing.JButton btnCountdownDelete;
    private javax.swing.JButton btnDeleteSong;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnLocation;
    private javax.swing.JButton btnPlaylistDown;
    private javax.swing.JButton btnPlaylistUp;
    private javax.swing.JComboBox<String> cbFileFormat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCountdown;
    private javax.swing.JLabel lbFileName;
    private javax.swing.JLabel lbLocation;
    private javax.swing.JLabel lbPlaylist;
    private javax.swing.JScrollPane spAudio;
    private javax.swing.JScrollPane spCountdown;
    private javax.swing.JTable tblCountdown;
    private javax.swing.JTable tblPlaylist;
    private javax.swing.JTextField tfFileName;
    private javax.swing.JTextField tfLocation;
    // End of variables declaration//GEN-END:variables
}
