/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.randomplaydanceplaylistgenerator2;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.*;
import javax.swing.UIManager;
import java.io.*;
import java.nio.file.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author benny
 */
public class MainFrameFlatLaf extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrameFlatLaf.class.getName());
    final JFileChooser fc, fcFolder;
    DefaultTableModel dtmCountdown, dtmPlaylist;
    String countdownCanonicalPath;

    /**
     * Creates new form MainFrameFlatLaf
     */
    public MainFrameFlatLaf() {
        try { // set look of GUI
            UIManager.setLookAndFeel( new FlatDarkLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        initComponents();
        getContentPane().setBackground(new java.awt.Color(60, 63, 65));
        
        // initialise countdown table and set canon path
        tblCountdown.setDefaultEditor(Object.class, null);
        final File folder = new File("./res/countdown-audios");
        updateCountdowns(folder);
        try {
            countdownCanonicalPath = folder.getCanonicalPath();
        } catch (IOException ex) {
            System.getLogger(MainFrameFlatLaf.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }        
        
        // initialise playlist table
        tblPlaylist.setDefaultEditor(Object.class, null);
        
        // initialise file/folder choosers
        fc = new JFileChooser();
        fcFolder = new JFileChooser();
        fcFolder.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLocation = new javax.swing.JLabel();
        btnAddFile = new javax.swing.JButton();
        btnAddFolder = new javax.swing.JButton();
        spCountdown = new javax.swing.JScrollPane();
        tblCountdown = new javax.swing.JTable();
        spAudio = new javax.swing.JScrollPane();
        tblPlaylist = new javax.swing.JTable();
        tfLocation = new javax.swing.JTextField();
        btnLocation = new javax.swing.JButton();
        lbCountdown = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnCountdownAdd = new javax.swing.JButton();
        btnCountdownDelete = new javax.swing.JButton();
        btnDeleteSong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RPD Playlist Generator");
        setMinimumSize(new java.awt.Dimension(700, 420));

        lbLocation.setText("Export Location");

        btnAddFile.setText("Add File");
        btnAddFile.addActionListener(this::btnAddFileActionPerformed);

        btnAddFolder.setText("Add Folder");
        btnAddFolder.setToolTipText("");
        btnAddFolder.addActionListener(this::btnAddFolderActionPerformed);

        tblCountdown.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spCountdown.setViewportView(tblCountdown);

        tblPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "FilePath", "Duration"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spAudio.setViewportView(tblPlaylist);

        btnLocation.setText("Select Location");
        btnLocation.addActionListener(this::btnLocationActionPerformed);

        lbCountdown.setText("Countdown Audio");

        btnClear.setForeground(new java.awt.Color(255, 0, 0));
        btnClear.setText("Clear Songs");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnExport.setForeground(new java.awt.Color(0, 255, 0));
        btnExport.setText("Export");
        btnExport.addActionListener(this::btnExportActionPerformed);

        btnCountdownAdd.setText("Add Countdown Audio");
        btnCountdownAdd.addActionListener(this::btnCountdownAddActionPerformed);

        btnCountdownDelete.setText("Delete Countdown Audio");
        btnCountdownDelete.addActionListener(this::btnCountdownDeleteActionPerformed);

        btnDeleteSong.setText("Delete Song");
        btnDeleteSong.addActionListener(this::btnDeleteSongActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExport))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCountdownDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(btnCountdownAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCountdown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spCountdown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 241, Short.MAX_VALUE)
                                .addComponent(btnAddFolder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteSong))
                            .addComponent(spAudio))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCountdown, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddFile)
                        .addComponent(btnAddFolder)
                        .addComponent(btnDeleteSong)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spCountdown, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCountdownAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCountdownDelete))
                    .addComponent(spAudio, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocation)
                    .addComponent(btnClear)
                    .addComponent(btnExport))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(712, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFolderActionPerformed
        int returnVal = fcFolder.showOpenDialog(MainFrameFlatLaf.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File folder = fcFolder.getSelectedFile();
            File[] listOfFiles = folder.listFiles();
            if (listOfFiles != null) {
                for (File file : listOfFiles) {
                    if (file.isFile()) {
                        addToPlaylist(file);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnAddFolderActionPerformed

    private void btnAddFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFileActionPerformed
        int returnVal = fc.showOpenDialog(MainFrameFlatLaf.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            addToPlaylist(file);
        }
    }//GEN-LAST:event_btnAddFileActionPerformed

    private void addToPlaylist(File file) {
        Object[] fileAttributes = new Object[3];
        fileAttributes[0] = file.getName();
        fileAttributes[1] = file.getPath();
        fileAttributes[2] = file.length();
        dtmPlaylist = (DefaultTableModel) tblPlaylist.getModel();
        dtmPlaylist.addRow(fileAttributes);
    }
    
    private void btnCountdownAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountdownAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCountdownAddActionPerformed

    private void updateCountdowns(File folder) {
        File[] listOfFiles = folder.listFiles();
        if (listOfFiles != null) {
            ArrayList<Object[]> fileList = new ArrayList<>();
            for (File file : listOfFiles) {
                if (file.isFile()) { // add each countdown to list
                    Object[] fileAttributes = {file.getName()};
                    fileList.add(fileAttributes);
                }
            }
            dtmCountdown = (DefaultTableModel) tblCountdown.getModel();
            dtmCountdown.setRowCount(0);
            for (Object[] row : fileList) {
                dtmCountdown.addRow(row);
            }
        }
    }
    
    private void btnCountdownDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountdownDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCountdownDeleteActionPerformed

    private void btnLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationActionPerformed
        int returnVal = fcFolder.showOpenDialog(MainFrameFlatLaf.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File folder = fcFolder.getSelectedFile();
            tfLocation.setText(folder.getPath());
        }
    }//GEN-LAST:event_btnLocationActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        dtmPlaylist = (DefaultTableModel) tblPlaylist.getModel();
        dtmPlaylist.setRowCount(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // data validation
        int countdownIndex = getSelectedCountdownIndex();
        if (countdownIndex == -1) return;
        if (isPlaylistEmpty()) return;
        if (!isPathValid()) return;
        
        // get selected countdown
        dtmCountdown = (DefaultTableModel) tblCountdown.getModel();
        String selectedCountdown = dtmCountdown.getValueAt(countdownIndex, 0).toString();
        
        try { // write
            
            List<String> command = new ArrayList<>();
            command.add("ffmpeg");
            command.add("-y");

            // add each file as input
            for (int i = 0; i < dtmPlaylist.getRowCount(); i++) {
                command.add("-i");
                command.add(countdownCanonicalPath + "/" + selectedCountdown);

                command.add("-i");
                command.add(dtmPlaylist.getValueAt(i, 1).toString());
            }

            // build filter_complex
            StringBuilder filter = new StringBuilder();
            int totalInputs = dtmPlaylist.getRowCount() * 2;

            for (int i = 0; i < totalInputs; i++) {
                filter.append("[").append(i).append(":a]");
            }
            filter.append("concat=n=").append(totalInputs).append(":v=0:a=1[out]");

            command.add("-filter_complex");
            command.add(filter.toString());

            command.add("-map");
            command.add("[out]");
            
            command.add("-ac");
            command.add("2");

            command.add("-ar");
            command.add("44100");

            command.add(tfLocation.getText() + File.separator + "output.mp3");

            ProcessBuilder pb = new ProcessBuilder(command);
            pb.inheritIO();

            Process process = pb.start();
            process.waitFor();
            
            JOptionPane.showMessageDialog(this, "Export complete!");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Export failed: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnDeleteSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteSongActionPerformed
    
    private int getSelectedCountdownIndex() {
        int selectedRow = tblCountdown.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(rootPane,
                "No countdown selected",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        return selectedRow;
    }
    
    private boolean isPlaylistEmpty() {
        if (tblPlaylist.getRowCount() == 0) {
            JOptionPane.showMessageDialog(rootPane,
                "Playlist is empty",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return true;
        } return false;
    }
    
    private boolean isPathValid() {
        String filepath = tfLocation.getText();
        if (!filepath.equals("")) {
            try {
                Paths.get(filepath);
                return true;
            } catch (InvalidPathException | NullPointerException ex) {} 
        } 
        JOptionPane.showMessageDialog(rootPane,
            "Export path isn't valid",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrameFlatLaf().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFile;
    private javax.swing.JButton btnAddFolder;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCountdownAdd;
    private javax.swing.JButton btnCountdownDelete;
    private javax.swing.JButton btnDeleteSong;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnLocation;
    private javax.swing.JLabel lbCountdown;
    private javax.swing.JLabel lbLocation;
    private javax.swing.JScrollPane spAudio;
    private javax.swing.JScrollPane spCountdown;
    private javax.swing.JTable tblCountdown;
    private javax.swing.JTable tblPlaylist;
    private javax.swing.JTextField tfLocation;
    // End of variables declaration//GEN-END:variables
}
