<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://apache.org" xmlns:xsi="http://w3.org" xsi:schemaLocation="http://apache.org http://apache.org">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>RandomPlayDancePlaylistGenerator2</artifactId>
    <version>1.1</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>25</maven.compiler.release>
        <exec.mainClass>com.mycompany.randomplaydanceplaylistgenerator2.RandomPlayDancePlaylistGenerator2</exec.mainClass>
    </properties>
    
    <dependencies>
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf</artifactId>
            <version>3.7.1</version>
        </dependency>
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.7.1</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <mainClass>com.mycompany.randomplaydanceplaylistgenerator2.RandomPlayDancePlaylistGenerator2</mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.akathist.maven.plugins.launch4j</groupId>
                <artifactId>launch4j-maven-plugin</artifactId>
                <version>2.5.3</version>
                <executions>
                    <execution>
                        <id>l4j-clui</id>
                        <phase>package</phase>
                        <goals>
                            <goal>launch4j</goal>
                        </goals>
                        <configuration>
                            <headerType>gui</headerType>
                            <jar>${project.build.directory}/${project.build.finalName}-jar-with-dependencies.jar</jar>
                            <outfile>${project.build.directory}/RandomPlayDanceGenerator.exe</outfile>
                            <downloadUrl>https://adoptium.net</downloadUrl>
                            <classPath>
                                <mainClass>com.mycompany.randomplaydanceplaylistgenerator2.RandomPlayDancePlaylistGenerator2</mainClass>
                            </classPath>
                            <jre>
                                <path>%JAVA_HOME%</path>
                                <minVersion>25</minVersion>
                                <jdkPreference>preferJre</jdkPreference>
                            </jre>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>